### ISSUE TITLE
Not really an issue, but...

### ISSUE THREAD

**Issue by byteslash** [eswann/Mapster#10]
Can you provide a really simple, end to end sample asp.net mvc project? i am new to object mappers and i am really struggling with configuration right now and while the readme does tell how the lib functions, there is nothing on how to actually get it up and running

**Comment by LorenDorez** [comment]
Try looking at this article, it has a basic example

https://ericswann.wordpress.com/2015/03/14/nozus-step-3-adding-asp-net-identity-to-mvc-6/
