### ISSUE TITLE
Record type mapping doesn't work as expected

### ISSUE THREAD

**Issue by arntj** [eswann/Mapster#103]
Hello.

The Mapster documentation has a section on "Conversion from/to Record Types", which is exactly what I need, including an example code snippet.

But when I copy and paste the exact code example into an empty console project, I get a Microsoft.CSharp.RuntimeBinder.RuntimeBinderException. This is using Mapster 2.6.1. What am I doing wrong here?

Here is my code, for reference:
```
using Mapster;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
namespace TestMapster
{
    class Program
    {
        class Person
        {
            public string Name { get; }
            public int Age { get; }
 
            public Person(string name, int age)
            {
                this.Name = name;
                this.Age = age;
            }
        }
 
        static void Main(string[] args)
        {
            var src = new { Name = "Mapster", Age = 3 };
            var target = src.Adapt<Person>();
        }
    }
}
```

**Comment by chaowlert** [comment]
Class must be public (and should not be nested) to allow dynamic to work.

**Comment by arntj** [comment]
@chaowlert Thanks for your reply. I moved the Person class to a different file and made it public, but I still get the same error.

**Comment by chaowlert** [comment]
I need to find time to fix this issue, with short form `src.Adapt<Person>()`, this requires `dynamic` and it doesn't support non-public class at all. Even your `Person` class is public, but anonymous type `new { name = "Mapster", Age = 3 }` is not public.

To fix this pls change your command to `var target = src.BuildAdapter().AdaptToType<Person>();`.

**Comment by arntj** [comment]
@chaowlert Now it works, thanks.
