### ISSUE TITLE
RequireDestinationMemberSource single instance (non-global) usage

### ISSUE THREAD

**Issue by dotnetchris** [eswann/Mapster#105]
Is there any way in Mapster to indicate I want to apply this criteria to a specific mapping action instead of globally? Maybe something along the lines of:

```c#
TypeAdapter.Adapt<Staff, StaffDto>(staff, requireDestinationMemberSource: true);  
```

Mapping data to a DTO, generally I would expect every single property filled on the DTO and error if it can't. However this scenario does not often apply for model to model mapping such as applying transformative changes (e.g. update model). So optimally there should be a way to use this without being forced to either explicitly map everything or have no criteria assertion.

Dealing with this issue has always been my primary reason I just don't like AutoMapper. I want things to be explicit and verifable, however automapper provides a single `AssertConfigurationIsValid()` so either I'm required to spend tons of effort hand mapping(ignoring) or i'm blocked from `AssertConfigurationIsValid()`

**Comment by chaowlert** [comment]
Hi, you can have multiple setting sets by `new TypeAdapterConfig()`. And pass to adapt method `TypeAdapter.Adapt<Staff, StaffDto>(staff, config)`.

**Comment by dotnetchris** [comment]
Policy based, even better. Awesome.

**Comment by suntereo** [comment]
I'm have the same requirement but am using [Attribute base-Code generation](https://github.com/MapsterMapper/Mapster/wiki/Attribute-base-Code-generation). Is there any way to achieve this with Attribute base-Code generation?
