### ISSUE TITLE
RuntimeBinderException if TSource is a non public class

### ISSUE THREAD

**Issue by eric-b** [eswann/Mapster#109]
Hi,

FYI this use case is not supported:

	void Main()
	{
		var sourceOptions = new SourceOptions();

		// RuntimeBinderException thrown here ("Cannot invoke a non-delegate type")
		sourceOptions.Adapt<DestinationOptions>(); 
	}
	
	internal class SourceOptions
	{
		public string Value { get; set; }
	}
	
	internal class DestinationOptions
	{
		public string Value { get; set; }
	}

Alternative 1:

	void Main()
	{
		var sourceOptions = new SourceOptions();
		sourceOptions.Adapt<DestinationOptions>();
	}
	
	public class SourceOptions
	{
		public string Value { get; set; }
	}
	
	internal class DestinationOptions
	{
		public string Value { get; set; }
	}

Alternative 2:

	void Main()
	{
		var sourceOptions = new SourceOptions();
		sourceOptions.Adapt<SourceOptions, DestinationOptions>(new DestinationOptions());
	}
	
	internal class SourceOptions
	{
		public string Value { get; set; }
	}
	
	internal class DestinationOptions
	{
		public string Value { get; set; }
	}

**Comment by chaowlert** [comment]
Hi, this problem should be fixed in Mapster 3.0. Thx for reporting.

**Comment by eric-b** [comment]
Thanks, I tested on v3 :-)
