### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by centur** [eswann/Mapster#11]
subj

**Comment by chaowlert** [comment]
I just joined this project. I will do by best to support.

**Comment by centur** [comment]
Cool, great to see the project is revitalized

**Comment by centur** [comment]
Also - where to send pull requests in case of small fixes\examples - to your branch or to eswann (e.g. this  branch)

**Comment by chaowlert** [comment]
I guess PR should go to this repo (eswann).
