### ISSUE TITLE
Mapping collection with derived types not working properly

### ISSUE THREAD

**Issue by Ic3xX** [eswann/Mapster#119]
In my project i currently use Mapster 3.1.1. I tried to use the new feature for mapping a collection of derived types. I think this is not working correctly or the use case is different.

Assume the following structure:

    public abstract class Car
    {
        public Guid Id { get; set; }

        public string Model { get; set; }
    }

    public abstract class CarDto
    {
        public Guid Id { get; set; }

        public string Model { get; set; }
    }

    public class Mercedes: Car
    {
        
    }

    public class MercedesDto : CarDto
    {
        
    }

    public class Opel : Car
    {

    }

    public class OpelDto : CarDto
    {
        
    }

Mapper configuration:

TypeAdapterConfig<Car, CarDto>.NewConfig()
                .Include<Opel, OpelDto>()
                .Include<Mercedes, MercedesDto>();

Mapper test:

var listWithCars = new List<Car> { new Opel(), new Mercedes() };

//Will throw an error cannot map OpelInfo to MercedesInfo
var mappedCars = listWithCars.Adapt<IList<CarDto>>();

I saw the testcase when mapping just one type. This works just fine. Using more than one type will break the mapping.

**Comment by chaowlert** [comment]
thx for reporting, i will fix soon

**Comment by chaowlert** [comment]
i just release 3.1.3, pls test whether it can solve your issue.

**Comment by Ic3xX** [comment]
Thank you very much, now its working in 3.1.3.
