### ISSUE TITLE
Different behaviour for ignored attributes in 3.x.x ?

### ISSUE THREAD

**Issue by Ic3xX** [eswann/Mapster#120]
I observed different behaviour when using attributes to ignore specific member. Not sure which is correct.

For version 2.x.x the attributes on the source type did not take affect on the mapping, only the target.

For version 3.x.x the attributes on both source and target types take affect on the mapping.

Let's say we have the following models:

public class A 
{
     [AdaptIgnore]
     public Guid Id { get; set; }

     public Guid NextId { get; set; }
}

public class B
{
     public Guid Id { get; set; }

     [AdaptIgnore]
     public Guid NextId { get; set; }
}

Version 2.x.x :
A.Adapt.B // Only Id is mapped
B.Adapt.A // Only NextId is mapped

Version 3.x.x :
A.Adapt.B // Nothing is mapped
B.Adapt.A // Nothing is mapped

**Comment by chaowlert** [comment]
Yeah, sorry, it is breaking change. To ignore only one side pls use following:

    config.IgnoreMember((member, side) => member.HasCustomAttribute(typeof(NotMapAttribute)) && side == MemberSide.Source);

You might need to create new attribute, since `AdaptIgnore` will ignore both sides.

**Comment by Ic3xX** [comment]
Okay thank you. I will change my code to match the new behaviour.
