### ISSUE TITLE
Noticed an issue with require explicit mappings

### ISSUE THREAD

**Issue by eswann** [eswann/Mapster#14]
I had an issue where my contract type was string[] and was mapping to IList&lt;string&gt;.  When mapping with RequireExplicitMapping = true, this fails with a message that the mapping doesn't exist between string[] and IList&lt;string&gt;.  I'm thinking that conversions between different enumerable types (of the same underlying type) should probably be ignored in this case.  I'll try to add a test case when I get a chance if you don't have bandwidth to look into it.  Don't want to lose the issue though.

**Comment by chaowlert** [comment]
Thank you for help testing. I already fixed this case & created new version on Nuget.
