### ISSUE TITLE
Explicit mapping throws on mapping Enum -> String

### ISSUE THREAD

**Issue by eswann** [eswann/Mapster#16]
When RequireExplicitMapping is true, the mapping complains that a map doesn't exist between the enum type and string.  Had to explicitly map the property to make it work. 

TypeAdapterConfig<ResponseMessage, Results.ResponseMessage>.NewConfig()
				.Map(dest => dest.Type, src => src.Type.ToString());

Shouldn't need that explicit map line and it negates any perf optimizations in the mapper.

This works fine if an explicit call to compile is not conducted.  But if compile is called, it complains about what should probably be an accepted primitive conversion.  I messed with it a little bit but not sure the best place to implement this check.

**Comment by eric-swann-q2** [comment]
The second commit in my pull request shows this issue via some added unit tests.
