### ISSUE TITLE
With explicit mapping turned on...map from IList<TSrc> to List<TDest> fails even though underlying types are mapped.

### ISSUE THREAD

**Issue by eric-swann-q2** [eswann/Mapster#17]
Looks like with explicit mapping enabled...a call to map IList<TSrc> to List<TDest> where TSrc and TDest are mapped is throwing.

**Comment by eric-swann-q2** [comment]
This is fixed with latest commits.

**Comment by eswann** [comment]
@chaowlert Thanks a lot for tracking down these issues...very excited that you took over this project and took it to the next level.  I'm excited about using this product again!  Now using it on my new project.
