### ISSUE TITLE
Mapping flat to hierarchical object in v2. Potential un-flattening breaking change

### ISSUE THREAD

**Issue by centur** [eswann/Mapster#20]
Previously for mapping from flat request to more structured type I was using this configuration
```
TypeAdapterConfig<UserCreateRequest, NewUserDetails>.NewConfig()
  .Map(d => d.AccountLocation, s => "EU")
  .Map(d => d.UserProfile, s =>TypeAdapter.Adapt<UserCreateRequest>(s))
;
```
Effectively what it does is un-flattening.
Important note that now for this operation we need to specify target and source types in generic parametrization  for Adapt, like this (note **UserState** ):

```
TypeAdapterConfig<UserCreateRequest, NewUserDetails>.NewConfig()
  .Map(d => d.AccountLocation, s => "AU")
  .Map(d => d.UserProfile, s =>TypeAdapter.Adapt<UserCreateRequest, UserState>(s));
```

Otherwise compiler will complain with this:
>Error	CS0854	An expression tree may not contain a call or invocation that uses optional arguments	

Not a bug but worth to mention breaking change

**Comment by chaowlert** [comment]
I will create method overload rather than optional argument to fix this problem.

Anyway, with V2, you can map without calling to TypeAdapt ie.

```
TypeAdapterConfig<UserCreateRequest, NewUserDetails>.NewConfig()
  .Map(d => d.AccountLocation, s => "AU")
  .Map(d => d.UserProfile, s => s);
```

**Comment by centur** [comment]
:+1: that's cool, I think it wasn't working in v1 this way. Thanks
