### ISSUE TITLE
If only have a single constructor with parameters...map to parameters of constructor

### ISSUE THREAD

**Issue by eswann** [eswann/Mapster#28]
I'm currently building a system that is very DDD oriented...as such we only want to initialize objects (even value objects) that are in the domain model (and events) via constructors.  No manual assignment to properties (not even private assignment!)  We don't want to initialize via mapping to properties...period.  Always way to use the constructor  Would be cool if:
1) If object has a single (default) constructor with parameters, attempt to perform standard name/object mapping to the constructor parameters when creating the object.
2) Less important: If there are multiple constructors, possibly allow a specific constructor to be chosen (attribute?) and map to that constructor (Automatically, not using ConstructWith...)

Have too many other things on my plate to implement now...but want to add a placeholder here.

**Comment by chaowlert** [comment]
Cool idea! C#7 also promote this pattern as record class. https://github.com/dotnet/roslyn/issues/206 and this should support F# record types automatically.
