### ISSUE TITLE
Entity Framework + IQueryable Extensions

### ISSUE THREAD

**Issue by gabrielsimplicio** [eswann/Mapster#34]
Hi!
(Sorry my bad english)

I'm trying to use Entity Framework with Mapster, and call Project() method. This is my scenario:

Model classes:
```
public class Student
{
    [Key]
    public int IDStudent { get; set; }
    public string Name { get; set; }
    public DateTime BirthDate { get; set; }
    public virtual ICollection<School> Schools { get; set; }
}

public class School
{
    [Key]
    public int IDSchool { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public virtual ICollection<Student> Students { get; set; }
}
```
DTO's:
```
public class StudentDTO
{
    [Key]
    public int IDStudent { get; set; }
    public string Name { get; set; }
    public DateTime BirthDate { get; set; }
    public ICollection<SchoolDTO> Schools { get; set; }
}

public class SchoolDTO
{
    [Key]
    public int IDSchool { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public ICollection<StudentDTO> Students { get; set; }
}
```

When I try
```
var students = context.Student.Include(p => p.Schools).Project().To<StudentDTO>().ToList();
```
I'm getting the following error:
```
LINQ to Entities does not recognize the method 'StudentDTO Invoke(Student)' method, and this method cannot be translated into a store expression.
```
What am I missing?

This is an amazing project! Great job, guys!

Thank you!

**Comment by chaowlert** [comment]
Please update to V2.1.0. We just add support for `ICollection<>`, `IList<>` and `List<>` for projection. If it is still not working, pls help report.

**Comment by gabrielsimplicio** [comment]
I'm already using v2.1.0 :(
I made a [demo project](https://github.com/gabrielsimplicio/mapster-ef-demo).
Thanks!

**Comment by chaowlert** [comment]
Thank you! At this time, Pls try changing ICollection to IEnumerable. This should works. I will check it soon.

**Comment by chaowlert** [comment]
I just realize that there is circular reference in your model. Projection doesn't support circular reference yet. To make it works, you might need to remove one of collection out.

**Comment by chaowlert** [comment]
Anyway, how could you write above projection in linq?

**Comment by gabrielsimplicio** [comment]
Thanks for the quick reply!

Yes... Circular reference support could resolve.

I don't know if I got your question very well, but, for the linq projection between the models, this following code is enough, right?
```
context.Student.Include(p => p.Schools)
```
And mapping manually, in my case, just the first level is enough (Student -> ICollection<School>). The school's students don't matter.
(Again, sorry my bad english)

**Comment by chaowlert** [comment]
Yes with query `context.Student.Include(p => p.Schools)`, you can access to `Schools` and `Students` collection recursively because EF will create dynamic proxy, and data will load lazily when you access to `Schools` and `Students` collection.

But if you map to other types, I think there is no solution to support circular reference. For example, 
```
var students = from student in context.Student.Include(p => p.Schools)
               select new StudentDTO {
                   ID = student.ID,
                   Name = student.Name,
                   Schools = from school in student.Schools
                             select new SchoolDTO {
                                 ID = school.ID,
                                 Name = school.Name,
                                 Students = ?? //this will become endless
                             }
                   };
```

There are few ways to overcome this, first we might need to support MaxDepth (Mapster V1 supports this). I haven't implement MaxDepth in V2 because I think this solution is just workaround, it just can access recursively in limited levels. And we removed it because we already solve circular reference for type adapting (but not projection).
Another way, Mapster might also need to support dynamic proxies. This might be difficult but fun. If I have time, I might implement this.

At this time for your destination models, please change to make it does not having recursive properties. Or move back to Mapster V1 to use MaxDepth feature.

**Comment by chaowlert** [comment]
@gabrielsimplicio Another solution for you just come up. Rather than using projection, I think for your case, you can use adapt method instead. We can let EF infrastructure build query, and use Mapster to map type.

```
TypeAdaptConfig.GlobalSettings.Default.PreserveReference(true);
var students = context.Student.Include(p => p.Schools).Adapt<List<StudentDTO>>();
```

**Comment by gabrielsimplicio** [comment]
Ok, I got it. The second alternative worked for me. Thanks for the support!

**Comment by chaowlert** [comment]
I will close this one as there is no issue left. I had added more descriptive error message in #36.

For future implementation, we might add support for circular reference in projection if there are more use cases.

For now, we might use EF to query and call `Adapt `method instead of `Project`.
```
TypeAdaptConfig.GlobalSettings.Default.PreserveReference(true);
var students = context.Student.Include(p => p.Schools).Adapt<List<StudentDTO>>();
```

**Comment by EduardoMiguelCruz** [comment]
Hi!

I'm trying to do projection with circular references (EF core 2.1 one to many)
PreserveReference still does not work with projection ?
