### ISSUE TITLE
Combine Project and To LINQ projection methods

### ISSUE THREAD

**Issue by jbogard** [eswann/Mapster#39]
In AutoMapper, I combined the `Project.To` into one single method, `ProjectTo`. This is because `IQueryable` has an `ElementType` property, letting you infer `TSource`. So the final result is something like:

```
public static IQueryable<TDestination> ProjectTo<TDestination>(this IQueryable source) { }

var results = dbContext.Products.ProjectTo<ProductDto>().ToList();
```

That extra method call always looked funny but I needed it because you can't do partial generic parameter inference. But you can grab ElementType, no need to supply `TSource` as a generic parameter, only `TDestination`. So I obsolete'd the Project.To in favor of ProjectTo (without having to change too much of the internals). I saw you had a suggestion in #38 for a better "To" method, I'd do this first.

**Comment by chaowlert** [comment]
This is good idea. Thank you for info.
