### ISSUE TITLE
IgnoreNullValues(true) not working with x.Adapt<TDestination>()

### ISSUE THREAD

**Issue by BuzzDee3000** [eswann/Mapster#42]
Hi,
I have some trouble with values initialized in destination class constructor that becomes null after mapping.
It works if I will use `source.Adapt(new DestClass());` but not with `source.Adapt<DestClass>();`.

This is my excample code:
`    public class DestClass
    {
        public string Title { get; set; }
        public List<string> List { get; set; }
        public SubClass Sub { get; set; }

        public DestClass()
        {
            List = new List<string>();
            Sub = new SubClass();
            Title = "Hello";
        }
    }

    public class SourceClass
    {
        public string Title { get; set; }
        public List<string> List { get; set; }
        public SubClass Sub { get; set; }
    }

    public class SubClass
    {
        public string SubName { get; set; }
    }`

And my xUnit Test:
`        [Fact]
        public void DoNotOverrideWithNullTest()
        {            
            TypeAdapterConfig<SourceClass, DestClass>.NewConfig()
                .IgnoreNullValues(true);

            var source = new SourceClass();
            var dest = source.Adapt<DestClass>(); // Fails
            // var dest = source.Adapt(new DestClass()); // Work fine

            Assert.Equal("Hello", dest.Title);
            Assert.NotNull(dest.Sub);
            Assert.NotNull(dest.List);
        }`

I'm using the latest version vom nuget.

**Comment by chaowlert** [comment]
Thank you for report. We will fix soon.

**Comment by BuzzDee3000** [comment]
Thanks for the quick fix. Works fine for me.
I hope it will be merged soon. :-)
