### ISSUE TITLE
Still has an issue with mapping dictionaries

### ISSUE THREAD

**Issue by centur** [eswann/Mapster#44]
Mapster can't map `Dictionary<string,Foo>` to `Dictionary<string,Bar>` although there is a valid mapping between Foo and Bar

This is because Dictionary implements IEnumerable<KeyValuePair> which is immutable.

Throws:
```
Cannot convert immutable type, please consider using 'MapWith' method to create mapping: 
TSource: System.Collections.Generic.KeyValuePair`2[System.String,Foo] 
TDestination: System.Collections.Generic.KeyValuePair`2[System.String,Bar]
```

Simple configuration like this
```
TypeAdapterConfig<Dictionary<string, Foo>, Dictionary<string, Bar>>
  .NewConfig()
  .MapWith(x => x.ToDictionary(k => k.Key, v => v.Value.Adapt<Bar>()))
```
works well and fixes the problem

Is this possible to add such behaviour as default\global for `Dictionary` and `Dictionary<TK,TV>` ? 

As it's a bit inconvenient to explicitly configure all possible Dictionary combinations..

**Comment by chaowlert** [comment]
Problem is not IEnumerable, problem is KeyValuePair is immutable. This issue related to #28 where setter should set through constructor not properties.

If we solve #28, this problem should be solved. I will find time to support record type.
