### ISSUE TITLE
ForType Settings

### ISSUE THREAD

**Issue by Stalso** [eswann/Mapster#48]
Hello. I have some missunderstanding. I have example code

        public class SourceClass
        {
            public string A { get; set; }
            public string B { get; set; }
            public string C { get; set; }
        }
        public class DestClass
        {
            public string A { get; set; }
            public string B { get; set; }
            public string C { get; set; }
        }
        private void MappingTest()
        {
            var sourceItem = new SourceClass()
            {
                A = "A source",
                B = "B source",
                C = "C source",
            };
            
            TypeAdapterConfig<SourceClass, DestClass>.NewConfig().Map(dest => dest.A,
              src => string.Format("{0} {1}", src.A, "Add something To A"));

            // This mapping gives:
            // firstResult.A =  "A source Add something To A"
            // firstResult.B = "B"
            // firstResult.C = "C"
            var firstResult = TypeAdapter.Adapt<DestClass>(sourceItem);

            // This config should extend previous config
            TypeAdapterConfig<SourceClass, DestClass>.ForType().Map(dest => dest.C,
                src => string.Format("{0} {1}", src.C, "Add something To C"));

            // This mapping also gives:
            // secondResult.A = "A source Add something To A"
            // secondResult.B = "B"
            // secondResult.C = "C"
            // But It should give
            // secondResult.A = "A source Add something To A"
            // secondResult.B = "B"
            // secondResult.C = "C Add something To C"
            var secondResult = TypeAdapter.Adapt<DestClass>(sourceItem);

        }

As you see, second `ForType` config is not applied. I resolved this by calling on second (`ForType`) config `Compile()` method. Is it correct?

**Comment by chaowlert** [comment]
TypeAdapterConfig should be called at application startup. Once, we call TypeAdapter.Adapt, execution logic will be compiled. If we change the config after compilation, there will be no effect.

To solve this issue, you might create `new TypeAdapterConfig()` rather than using static method and pass config to adapt method. Then you can have different config per mapping.

Thank you for reporting issue, I will add error message, when changing config after compilation.

**Comment by Stalso** [comment]
Ok. But how can I create `new TypeAdapterConfig()` based on current settings (on global config)?

**Comment by chaowlert** [comment]
@Stalso This version still cannot create config based on another setting right now. There is also another ticket (#41) mention this. It is in TODO list.

**Comment by Stalso** [comment]
Thank you. Maybe then you will give me advice. I want to pass some papameters, when mapping entities. For example, I want to map some model in respect of current user in mvc controller,  and I should pass username to mapping. How can I implement this?  Maybe some anther tool will help me?

**Comment by chaowlert** [comment]
I also have plan for this. Other tool that can do this is AutoMapper. It allows to pass run-time value to mapping.

For current version of Mapster, you might need to map manually after mapping.

```
var dest = src.Adapt<DestClass>();
dest.UserId = this.User.Identity.Name;
```
