### ISSUE TITLE
Handling Null source objects 

### ISSUE THREAD

**Issue by shah-123** [eswann/Mapster#60]
In our coding we have a situation where source object doesn't have any value. E.g. We are getting user information from database, but id pass is not valid, so user object is null. 

One way if to sprinkle null check before invoking Adapt method
if (user != null)
{ 
    _adapter.Adapt<UserViewModel>(user)
}

If there better way to handle Null object in Mapster?

I have seen that AutoMapper supports something like below:
Mapper.CreateMap<User, UserViewModel>()
    .ConvertUsing<UserToUserViewModelConverter>();

class WsMembershipToDeMemberConverter
    : AutoMapper.ITypeConverter<User, UserViewModel>
{
    public UserViewModel Convert(AutoMapper.ResolutionContext context)
    {
        if (context == null || context.IsSourceValueNull) 
        { 
            return null;
        }

        var User = context.SourceValue as User;

        var UserViewModel = new UserViewModel();

        // conversion rules and logics here

        return UserViewModel 
    }
}

Do we have any such support? Any thing one can suggest so we don't have to sprinkle null check in entire code base.

**Comment by chaowlert** [comment]
Hi @shah-123,

Sorry for late reply.

This need to be fixed. Thank you for report.
Mapster already support mapping null value. But there is bug when we infer type of source object.
To workaround, specifying both sourceType and destinationType will solve the problem.

```
_adapter.Adapt<SourceType, DestinationType>(user);
```

With above configuration, when user is null, function will return null instead of error.

**Comment by shah-123** [comment]
Hi !!
When do we expect next release of Mapster?
Thanks,
Tejas

**Comment by chaowlert** [comment]
I have no plan yet. Please specify both source type and destination type to solve problem for now.

**Comment by brgrz** [comment]
> With above configuration, when user is null, function will return null instead of error.

Mapster just silently ignores null references for example 

`	.Map(dest => dest.PostName, src => src.Postcode.Name)`

if Postcode is null, it maps like all is good.

What if we want to throw an exception when dealing with null objects? Can't seem to find that configuration option anywhere.
