### ISSUE TITLE
Consider applying NameMatchingStrategy(NameMatchingStrategy.Flexible) to Dictionary<->Object mapping

### ISSUE THREAD

**Issue by kellyethridge** [eswann/Mapster#63]
Hello,

From what I can tell, the name matching strategy is only applied between two objects. It would be a big benefit for Dictionary<->Object mapping, especially when using PATCH methods in WebApi since json property names are usually camel-case/snake-case while classes are usually Pascal.

**Comment by chaowlert** [comment]
Yeah true, we should also apply name matching to dictionary.

**Comment by chaowlert** [comment]
Note: for performance reason, I added 2 strategies 
`NameMappingStrategy.ToCamelCase` is for Object to Dictionary 
`NameMappingStrategy.FromCamelCase` is for Dictionary to Object

`NameMappingStrategy.Flexible` is also working, but performance might be low.
