### ISSUE TITLE
Autocomplete not working in TypeAdapterConfig<>.Map<> Source

### ISSUE THREAD

**Issue by philippjenni** [eswann/Mapster#64]
AutoComplete doesn't work in VS2015 when I write TypeAdapterConfig<>.Map<> in Source Parameter. In Destination Parameter it works fine.

It would be nice if it works on source too.

Example: 
TypeAdapterConfig<Adresse, AdresseDetailDto>.NewConfig()
                .Map(dest => dest**.Id**, source => source.Id)

**Comment by chaowlert** [comment]
I'm so sorry. I can't reproduce this issue. Mine works correctly.

**Comment by philippjenni** [comment]
Sorry it doesnt work in Destination Parameter, and only when the command is not complete.

.Map(dest => dest. -> Not working
.Map(dest => des -> Working
.Map(dest => dest ,) -> Working

Can you reproduce this?

**Comment by philippjenni** [comment]
I have tested now with an other product. It looks like an bug in VS2015 Pro
