### ISSUE TITLE
Question: MapContext used with ProjectToType

### ISSUE THREAD

**Issue by philippjenni** [eswann/Mapster#66]
Hi,

I use Masper 2.4 an  have 2 questions:

1. I can't use MapContext in my Mapping. I receive an "Inaccesbile due Protection Level" Build Error. What i due i wrong. I have a static Mapper Class to Map the DTO's

2. How can i use MapContext in combination with ProjectToType?

Thanks for response
Philipp

**Comment by chaowlert** [comment]
Hi @philippjenni 

I just published 2.4.1 to fix MapContext. 

For ProjectToType please use following

```
using (var scope = new MapContextScope())
{
    scope.Context.Parameters["user"] = this.User.Identity.Name;
    var results = dbContext.Poco.ProjectToType<Dto>();
}
```

Before closing the scope, you must fetch the result (ie. ToList, First). Otherwise, you might get Null Exception.

**Comment by philippjenni** [comment]
Hi, 

Thanks for your fix. I will try it.

**Comment by philippjenni** [comment]
Hi, 

I have tested it now but i have an empty list and i don't know why. Here my Code stack

Reader

```
using (var scope = new MapContextScope())
{
  return Mapper.ConvertAdresseToAdresseOverviewDto(scope, query.Take(maximumRows).Skip(startRowIndex),
    this.GetWritePermissionRoles(currentUser), this.GetDeletePermissionRoles(currentUser)).ToList().AsQueryable();
}
```

Static Converter

```
internal static IQueryable<AdresseOverviewDto> ConvertAdresseToAdresseOverviewDto(MapContextScope scope, IQueryable<Adresse> query,
  List<int> editRoles, List<int> deleteRoles)
{
  scope.Context.Parameters["editRoles"] = editRoles;
  scope.Context.Parameters["deleteRoles"] = deleteRoles;
  return query.ProjectToType<AdresseOverviewDto>();
}

```

Mapper

```
TypeAdapterConfig<Adresse, AdresseOverviewDto>.NewConfig()
  .Map(dest => dest.Id, source => source.Id)
  .Map(dest => dest.Nachname, source => source.Nachname)
  .Map(dest => dest.Vorname, source => source.Vorname)
  .Map(dest => dest.RolesEdit, source => MapContext.Current.Parameters["editRoles"])
  .Map(dest => dest.RolesDelete, source => MapContext.Current.Parameters["deleteRoles"]);
```

Do you have an idee what i do wrong?

**Comment by philippjenni** [comment]
I have found the problem.

I has to use 
`scope.Context.Parameters.Add("editRoles",editRoles)`
instead of 
`scope.Context.Parameters["editRoles"] = editRoles;`
