### ISSUE TITLE
how to map just derived class properties (and exclude base class)

### ISSUE THREAD

**Issue by nsgaga** [eswann/Mapster#69]
Hi, 
(I'm referring to the 'source' type, I want to avoid mapping all inherited properties from base classes)
I've tried a few things fast, even MapToTargetWith(=> destination) to skip any mapping on the base, but then NoInherit doesn't work (seems) so the derived one is turned off as well (if I'm getting it right).
and btw. Mapster is looking great so far!
Thanks

**Comment by chaowlert** [comment]
In general, to ignore members, Mapster supports ignore member by names and by attributes.

```
TypeAdapterConfig<A,B>.NewConfig().Ignore("Prop1","Prop2");
TypeAdapterConfig<A,B>.NewConfig().IgnoreAttribute(typeof(CustomIgnoreAttribute));
```

Could you give reason behind and example why you would like to do this?

**Comment by nsgaga** [comment]
thanks for your response (and sorry on my slow response),
yes that's what I've done in the end, but I sort of need a more 'generic' solution:
- I want to map all the properties of the derived class (on the 'source' side, target isn't important here).
- I don't want any base class properties (as some naming/properties could clash w/ the target, resulting in 'silent bugs' which are very hard to catch, we've had those already).
problem is that I don't always know the target properties (or there could be many, think of it as a Db entity, and base classes are not really of interest (for mapping) but could have quite a few properties on their own - which potentially could create issues only. 
Of course, I know my base class properties, but e.g. that means Ignoring dozen or so, and we have this pattern repeating over and over with different base classes, so it's becoming tedious.
I just thought you may have some way of doing this easily.
Thanks
P.S. if you need a 'hands on' example I could create one, thought this might be enough, let me know

**Comment by chaowlert** [comment]
I see your point. I also would like Mapster to be able to configure by convention rather than config name by name. For now, you could ignore by names. For example:

```
var props = typeof(Source).GetProperties(BindingFlags.DeclaredOnly | BndingFlags.Public | BindingFlags.Instance).Select(p => p.Name).ToArray();
TypeAdapterConfig<Source, Dest>.NewConfig().Ignore(props);
```

Thank you for suggestion.

**Comment by nsgaga** [comment]
thanks! 
I didn't know it could do that (that 3rd overload w/ just names params), **it does seem to work fine** (just can't apply it to the `TypeAdapterConfig<BaseClass, Target>.NewConfig().Ignore(props);` (base class) but have to at the derived one directly, complains w/ empty collection 'expressions'),
that should do for me for now, thanks again
