### ISSUE TITLE
Mapping ObservableCollection<T> throws error

### ISSUE THREAD

**Issue by madben2000** [eswann/Mapster#7]
Mapping ObservableCollection<T> throws exception in ClassAdapter's Adapt-method at:

if (propertyModel.DestinationTransform == null)
                    {
                        propertyModel.Setter.Invoke(destination, destinationValue);
                    }

Anyway to solve this? Did not find a solution at this time...

**Comment by madben2000** [comment]
Solved it by extending CollectionAdapter's Adapt-method:

if (destinationType.IsGenericType)
            {
                #region CopyToList
                var adapterInvoker = _collectionAdapterModel.AdaptInvoker;

                IList<TDestinationElement> list;

                if (destinationType == typeof(ObservableCollection<TDestinationElement>))
                    list = destination == null ? new ObservableCollection<TDestinationElement>() : (ObservableCollection<TDestinationElement>)destination;
                else
                    list = destination == null ? new List<TDestinationElement>() : (List<TDestinationElement>)destination;

                if (_collectionAdapterModel.IsPrimitive)
                {
                    bool hasInvoker = adapterInvoker != null;
                    foreach (var item in source)
                    {
                        if (item == null)
                            list.Add(default(TDestinationElement));
                        else if (hasInvoker)
                            list.Add((TDestinationElement)adapterInvoker(null, new[] { item }));
                        else
                            list.Add((TDestinationElement)item);
                    }
                }
                else
                {
                    foreach (var item in source)
                    {
                        list.Add((TDestinationElement)adapterInvoker(null, new[] { item, false, (hasMaxDepth ? ReflectionUtils.Clone(parameterIndexes) : parameterIndexes) }));
                    }
                }

                return list;

                #endregion
            }

**Comment by madben2000** [comment]
Any concern with this solution?

**Comment by eswann** [comment]
Sorry Ben, I missed this because you closed the issue :).  Thanks for the fast resolution!  Can you do a pull request?

**Comment by chaowlert** [comment]
Hi, Mapster 2.0 now support ObservableCollection.
