### ISSUE TITLE
Error for .NetCore

### ISSUE THREAD

**Issue by vbfool** [eswann/Mapster#71]
I use Mapster in my .NetCore WebApi project，but when I read the Request.Body ,it made a exception.
When I remove the Mapster,It becomes well.

**Comment by chaowlert** [comment]
Mine works properly. What is the exception? Mapster had just upgraded to .NetCore 1.0. Is it possible that we need to install new version of .NetCore?

**Comment by vbfool** [comment]
I used RC2，and now I update to RTM，that's OK.Thanks
