### ISSUE TITLE
Mapping fails

### ISSUE THREAD

**Issue by Duracell1989** [eswann/Mapster#73]
Hello,

I've got an issue when trying to map from one implementation of an interface to another implementation of the same interface.
The _ToPocoWithConstuctorWithoutAllProperties_ fails (It uses only casts the object instead of using the ConstructUsing; thus giving a whole other lamdba expression).

See tests:
[WhenMapping.txt](https://github.com/eswann/Mapster/files/373699/WhenMapping.txt)

**_ToPocoWithOnlyConstuctorForAllProperties_**
GetMergedSettings => result.ConverterFactory.Target == {Mapster.Adapters.RecordTypeAdapter}

.Lambda #Lambda1<System.Func`2[Mapster.Tests.IPoco,Mapster.Tests.ToPocoWithOnlyConstuctorForAllProperties]>(Mapster.Tests.IPoco $var1)
{
    .If ($var1 == null) {
        null
    } .Else {
        .New Mapster.Tests.ToPocoWithOnlyConstuctorForAllProperties(
            $var1.Id,
            $var1.SubId)
    }
}

**_ToPocoWithPrivateSet_**
GetMergedSettings => result.ConverterFactory.Target == {Mapster.Adapters.ClassAdapter}
.Lambda #Lambda1<System.Func`2[Mapster.Tests.IPoco,Mapster.Tests.ToPocoWithPrivateSet]>(Mapster.Tests.IPoco $var1) {
    .If ($var1 == null) {
        null
    } .Else {
        .New Mapster.Tests.ToPocoWithPrivateSet(
            $var1.Id,
            $var1.SubId){
        }
    }
}

**_ToPocoWithConstuctorWithoutAllProperties_**
GetMergedSettings => result.ConverterFactory.Target == {Mapster.Adapters.PrimitiveAdapter}
.Lambda #Lambda1<System.Func`2[Mapster.Tests.IPoco,Mapster.Tests.ToPocoWithConstuctorWithoutAllProperties]>(Mapster.Tests.IPoco $var1)
{
    .If ($var1 == null) {
        null
    } .Else {
        (Mapster.Tests.ToPocoWithConstuctorWithoutAllProperties)$var1
    }
}

**Comment by chaowlert** [comment]
Hi,

Currently, Mapster supports mapping to constructors only if there is only one constructor (this specified in documentation https://github.com/eswann/Mapster#ConversionRecordType). I did it this way because  I think there should be no reason for record type to have multiple constructors.

If you would like to change this behavior, please take a look at `RecordTypeAdapter` and `ReflectionUtils.IsRecordType`.
