### ISSUE TITLE
Map condition for all properties of some type

### ISSUE THREAD

**Issue by satano** [eswann/Mapster#74]
Hello

Is it possible to create a map condition for all properties of given type? For example, we want to have a condition for string properties, so the values are not mapped, when source value is `null` or empty string (or even whitespace string). So in general, we need a map condition `!string.IsNullOrWhitespace(sourceValue)`. But we need it for all string properties.

So is there a way writing it only once, so we do not need to make conditions for all properties?

Stano

**Comment by chaowlert** [comment]
Hi,

If you map to new object, you can use [AddDestinationTransforms](https://github.com/eswann/Mapster#Transform). But if you would like to map to existing object, we might need a bit workaround by transforming whitespace to null, and then IgnoreNullValues

```
TypeAdapterConfig<TSource, TSource>
    .NewConfig()
    .AddDestinationTransforms((string x) => string.IsNullOrWhitespace(x) ? null : x);
TypeAdapterConfig<TSource, TDestination>
    .NewConfig()
    .IgnoreNullValues(true);
```

In this 2nd option, we need temp variable to perform mapping.

```
var temp = src.Adapt<TSource>();    //this mapping is to remove all whitespaces
temp.Adapt<TDestination>(dest);     //this is to map to destination
```

Hope this will help

**Comment by satano** [comment]
Thank you.
