### ISSUE TITLE
"Instances of abstract classes cannot be created" exception for classes with JObject properties

### ISSUE THREAD

**Issue by centur** [eswann/Mapster#75]
Hi, I'm getting a similar exception "Instances of abstract classes cannot be created." as in #52, except that I don't have nested collection of abstract types. 
Instead, I have DTOs with `JObject` prop (and `JObject` has a property of `JToken` type and `JToken` is abstract). 
Protected ctors and abstract classes are fine, but `JObject` breaks the things.

Interesting, that even if `JObject` is the type on both source and input DTOs (so technically it should not be mapped, just deep copied? ), mapster tries to go deeper and map all subtypes. Am I thinking about Mapster expected behaviour wrong ?

Is there any configuration setting to tell mapster not to create deep mapping substructure ? I tried to play with `ConstructUsing` for `JObject` to avoid defining it for every DTO, but that doesn't help

Here is the repro script for LINQPad (Latest Mapster 2.4.3 and latest Json.NET 9.0.1 are referenced)

```C#
void Main()
{
	string jsonText = @"
    {
      ""AA"": {
		""Zorder"": ""9999"",
        ""PageNumber"": 1,
        ""Id"": ""f494dba7-372c-458f-942e-ecab7c938fa7"",
        ""Created"": ""2016-05-27T16:36:18.4172629+10:00"",
        ""Type"": 18,
        ""Content"": """",
        ""Geometry"": """",
        ""BlendMode"": 1
      },
      ""Id"": ""c0000000-0000-0000-0000-000000000000"",
      ""TraceId"": ""bbbbbbbb-bbbb-bb11-1111-111111111111""
    }";

	var jObjData = JObject.Parse(jsonText);

	var input = new MainSrc
	{
		BaseId = 11,
		SrcId = 1123,
		LastItem = jObjData,
	};
	//var res = jObjData.DeepClone();
	//res.GetType().Dump();
	//input.Dump();

	WebDTOMapSetup.Verify();
	var output = input.Adapt<MainSrc, MainDest>();
	output.Dump();
}


public class WebDTOMapSetup
{
	static WebDTOMapSetup()
	{
		TypeAdapterConfig<MainSrc, MainDest>.ForType();
		//TypeAdapterConfig<JObject, JObject>.ForType().ConstructUsing(f=>(JObject)f.DeepClone() as JObject)
		;
	}
	public static void Verify() 	{ TypeAdapterConfig.GlobalSettings.Compile();}
}

abstract class SrcBase
{
	protected SrcBase() { }
	protected SrcBase(int baseid) { BaseId = baseid; }
	public int BaseId { get; set; }
}

abstract class DestBase
{
	protected DestBase() { }
	protected DestBase(int baseid) { BaseId = baseid; }
	public int BaseId { get; set; }
}

class MainSrc : SrcBase
{
	public int SrcId { get; set; }
	public JObject LastItem { get; set; }
}

class MainDest : DestBase
{
	public int DestId { get; set; }
	public JObject LastItem { get; set; }
}
```

**Comment by chaowlert** [comment]
I also have this issue. Problem is `JObject` contains internal setter like `Parent`, `Next`, `Previous` (which Mapster will translate type as class rather than primitive). Then, Mapster try to perform deep copy, but `Parent`, `Next`, `Previous` are `JToken` are abstract. Currently, I solve this problem by `MapWith` to perform direct copy.

```
TypeAdapterConfig<JObject, JObject>.NewConfig().MapWith(src => src);
TypeAdapterConfig<JArray, JArray>.NewConfig().MapWith(src => src);
TypeAdapterConfig<JValue, JValue>.NewConfig().MapWith(src => src);
TypeAdapterConfig<JToken, JToken>.NewConfig().MapWith(src => src);
```

**Comment by centur** [comment]
You can close this issue if you want, search should help others who may stumble over the same problem

**Comment by chaowlert** [comment]
Do you have idea to improve this? Will it help if I add another method explicitly like `TypeAdapterConfig.Default.AddPrimitiveType<JObject>()`? If you have better name or better idea, pls suggest.

**Comment by centur** [comment]
I actually like the syntax we currently have: `TypeAdapterConfig<JArray, JArray>.NewConfig().MapWith(src => src);`.
It's clear and explicit and it doesn't add any extra methods to know about, so user uses the same, already known grammar set for this library. Also it helps when you're searching for a particular mapping - I can search for all lines using same pattern - `TypeAdapterConfig<JValue` - finds all mappings from `JValue`
and `TypeAdapterConfig<[^,],JValue>` finds me all mappings to `JValue`.

It may be worth to put an extra line or two in docs about this, as I'm sure that many users map objects  that are coming from API (cross-domain boundary) e.g. in Json or XML or other cross-platform format.

**Comment by chaowlert** [comment]
I just added a couple of lines for MapWith in doc.
