### ISSUE TITLE
Map private fields

### ISSUE THREAD

**Issue by hpcsc** [eswann/Mapster#79]
Hi,

Is there anyway to map private fields? I'm not able to find any settings to do that

Thanks
Regards,

**Comment by chaowlert** [comment]
You might need to add public property with private setter. Mapster doesn't support private field.

**Comment by hpcsc** [comment]
thanks for the reply, is it possible to make it configurable whether it should find private fields?

The reason is: I want to use this for mapping from domain objects to persistence/data models. I don't want to expose internal fields of domain objects and prefer to keep those internal details as private fields.

Thanks

**Comment by chaowlert** [comment]
I might add support for this in the future through attribute. For now, you can extend via `ValueAccessingStrategy`. You can look at this as example ([link](https://github.com/eswann/Mapster/blob/master/src/Mapster/ValueAccessingStrategy.cs#L58-L66)). After that, you can add by `TypeAdapterConfig.GlobalSettings.Default.Settings.ValueAccessingStrategies .Add(privateFieldAccessingStrategy)`

**Comment by hpcsc** [comment]
thanks, I managed to map from private fields to other model by replicating the method that you mentioned in the above link
however mapping back from other model to private fields is not working. Do you know where should I look into to make mapping back work?
BTW, is there any high level document on how this library is structured?

**Comment by chaowlert** [comment]
I haven't documented this since it is a bit advance. If I have free time I might document about this.

To map back, you can copy from `ClassAdapter` and change here ([link](https://github.com/eswann/Mapster/blob/master/src/Mapster/Adapters/ClassAdapter.cs#L26)) and here ([link](https://github.com/eswann/Mapster/blob/master/src/Mapster/Adapters/ClassAdapter.cs#L127)). Unfortunately, `ClassAdapter` is internal, you might need to copy whole code rather than just derive. 

To apply, use `TypeAdapterConfig.GlobalSettings.Rules.Add(new ClassWithPrivateFieldAdapter().CreateRule())`.

**Comment by chaowlert** [comment]
Another good way, easier, and it will help others, you can fork this repo, and create new class `MappingPropertyAttribute`. Whenever properties or fields decorated with this attribute, Mapster should be able to find it.

```
[MappingProperty]
private string HiddenProp { get; set; }
```

To make it a bit more advance, this attribute should be able to rename property or field.

```
[MappingProperty("NameMatchedWithSource")]
private string HiddenProp { get; set; }
```

After that you can change this method ([link](https://github.com/eswann/Mapster/blob/master/src/Mapster/Utils/ReflectionUtils.cs#L27-L38)) to be able to find `MappingPropertyAttribute`. Now you no more need `PrivateFieldAccessingStrategy` and `ClassWithPrivateFieldAdapter`.

If you finish, please create pull request with unit test. I will publish right away.

**Comment by hpcsc** [comment]
thanks a lot

I would love to give it a try, but I prefer to let mapping-related stuffs out of domain classes (for the same reason that I don't want persistence-related stuffs in a domain class), so I'm thinking about something like this:

Configure for a specific mapping:
 
```
TypeAdapterConfig<TSource, TDestination>
    .NewConfig()
    .Map("_somePrivateFieldInTSource", "SomePropertyInTDestination");
```

This also allows specifying mapping using string, in addition to lambda/expression, although it loses the strongly-typed.

And also maybe create an additional private field accessing strategy

What's your opinion?

**Comment by chaowlert** [comment]
I have no problem with your api design. In fact, this is even easier. With this, you no need to change method I mentioned in previous comment.

**Comment by hpcsc** [comment]
sure, I'll attempt it tonight and update when there's some progress

**Comment by chaowlert** [comment]
Close from #81
