### ISSUE TITLE
The specified type member '<Property>' is not supported in LINQ to Entities

### ISSUE THREAD

**Issue by janhartmann** [eswann/Mapster#80]
I just recently stubmled across this great library, but ran into a possible limitation (most likely a Entity Framework limitation) but I was wondering if this is a case that could be covered with Mapster. 

Take this Entity and DTO:

```cs
public class Site
{
    public Guid Id { get; set; }

	public double[] Extent => new[] {ExtentMinX, ExtentMinY, ExtentMaxX, ExtentMaxY};

	public double ExtentMinX { get; set; }

	public double ExtentMinY { get; set; }

	public double ExtentMaxX { get; set; }

	public double ExtentMaxY { get; set; }
}

public class SiteView
{
	public double[] Extent { get; set; }
}
```

Throws this exception:

> "The specified type member 'Extent' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported."

Using this:

```cs
private readonly IEntityReader<Site> _reader;

// ...

return _reader.Query()
                .Where(s => s.Id == query.Id)
                .ProjectToType<SiteView>()
                .SingleOrDefault();
```

However I can come around this by letting EF finish the operation and map afterwards:

```cs
var site = _reader.Query().SingleOrDefault(s => s.Id == query.Id);
return project.Adapt<SiteView>();
```

Which feels a bit hacky for me, is this something Mapster can handle for me?

All the best,
Jan

**Comment by chaowlert** [comment]
Hi @janhartmann,

This is EF limitation, `ProjectToType` is more efficient in querying data, but it is limited to what EF can do. From your example, when you used `ProjectToType` it will translate into sql like this

```
select Extent from Sites where Id = @id
```

Since there is no `Extent` column in table, EF will not allow this operation. You can use `Adapt` because you need to query whole record first and then mapping type later.

So to fix this, you can add config

```
TypeAdapterConfig<Site, SiteView>.NewConfig()
    .Map(dest => dest.Extent, src => new[] { src.ExtentMinX, src.ExtentMinY, src.ExtentMaxX, src.ExtentMaxY});
```

**Comment by janhartmann** [comment]
Perfect, thanks - I'll create those mappings using DI.
