### ISSUE TITLE
AutoMapper 5 benchmarks

### ISSUE THREAD

**Issue by jbogard** [eswann/Mapster#83]
FYI the benchmark numbers for AutoMapper are pretty out of date now, the 5.0/5.1 release numbers are significantly different.

Though honestly not a huge fan of the way ExpressMapper did their benchmarks - with gigantic lists instead of calling Map over and over again. I guess both are important but I rarely get people mapping things with a million items in it, more that it's a big website and a lot of things calling Map.

**Comment by chaowlert** [comment]
Thx for update and glad to hear this! I will update content soon.
