### ISSUE TITLE
.Map doesn't 'honor' previous config settings - like .ConstructUsing...

### ISSUE THREAD

**Issue by nsgaga** [eswann/Mapster#84]
Hi,
I have something like: 

    TypeAdapterConfig<IEntity, EntityViewModel>.ForType() //.NewConfig()    
        .ConstructUsing(entity => Container.Resolve<EntityFactory>()(entity)); // a bit simplified    
        // .Map ... (I uncomment this to get the issue)
    TypeAdapterConfig<EntityViewModel, IEntity>.ForType() //.NewConfig()    
        .ConstructUsing(x => null)    
        .Ignore(props);    

...defined for all my view models/entity combinations.
(I'm using ConstructUsing to avoid 'no default constructor' exception and also provide .ctor for deep hierarchy mappings - which is another issue I have)
  
but when I add (uncomment)

    .Map(dest => dest.SomeCollectionProperty,
        src => src.SomeCollectionProperty.Select(x => Container.Resolve<PropertyViewModelFactory>()(x)).ToList())

...**I'm again getting exceptions that PropertyViewModel doesn't have default .ctor** (even though I have ConstructUsing defined, for that VM/entity, above that line, if order is of importance I guess not).  

I traced this to BaseAdapter and `var constructUsing = arg.Settings.ConstructUsingFactory?.Invoke(arg);` which is 'null' regardless of what I have specified.  
Seems like I'm not actually setting the right configuration, or not the 'global one' ? not sure.  

And as to 'why' I'm doing the .Map in the first place,
I did try just to let 'deep mapping' work itself but I'm getting various issues when mapping IEnumerable<ChildEntity> -> List<ChildViewModel> properties. Most notably that about 'modifying the underlining collection' (mentioned [here](https://github.com/eswann/Mapster/issues/68) but that fix, I have the latest code and version, doesn't work for me, or I can't actually apply that to my code). I tried tracking that but that only gets me to that expression factory  and not sure how to get any sensible info out of that, so I gave up (for now) trying to do the proper 'deep' mapping - instead I figured I could manually specify mapping for some of the problematic list / collection properties - and then I ran into the above problem.  
Any suggestions are welcome!
Thanks

**Comment by chaowlert** [comment]
Mapster should perform 'deep mapping' by default. I wasn't understand entirely about the issue. But `.Map(dest => dest.SomeCollectionProperty,  src => src.SomeCollectionProperty.Select(x => Container.Resolve<PropertyViewModelFactory>()(x)).ToList())`, seemed like it is duplicate with what Mapster does. At this point, Mapster doesn't use value you suggest, Mapster will create new list and create new PropertyViewModel for each item (and traverse through all children of PropertyViewModel) in order to perform deep mapping. .

If you wouldn't like Mapster to create new object for properties, you can set [ShallowCopyForSameType](https://github.com/eswann/Mapster#ShallowCopy) to `true`.

Another option is remove above `.Map` setting and add `TypeAdapterConfig<SomeProperty, PropertyViewModel>.NewConfig().ConstructUsing(src => Container.Resolve<PropertyViewModelFactory>()(src))` in order to tell Mapster how to create PropertyViewModel properly.

**Comment by nsgaga** [comment]
Hi, 
Thanks a lot for your response, 
that actually helped me set up things properly (and solve the issue).
**What you said that `.Map` is duplicate - it actually was in many ways.**

I didn't realize that the .Map is not actually a projection, and **my map (src expression part) was wrongly returning the destination property** - and map was then performed on VM --> VM not entity -> VM - which wasn't registered and was failing (and that behaved like .Map not honoring my previous configuration setup). I've figured that after some more debugging through your source code and watching your argument/context variables there (source code was invaluable).
**I.e. if I had .ConstructUsing defined (as I have), my `Container.Resolve<PropertyViewModelFactory>
()(x)` was then redundant** and actually just making problems.

Anyhow TL;DR - as soon as I removed that and just made simple proper map, I realized where 'deep hierarchy' was failing (in my code, hierarchy mapping is somewhat tricky done this way that I want, with custom DI and all, and wasn't set up properly but before that point I wasn't sure what / where to look for),
and **now 'deep hierarchy' 'just works' on its own - like you said it should**.

I guess I just needed some reassuring :)

And in the end everything seems to be just fine with Mapster - except that .Map isn't 'intuitive' enough to me at least (and that's the only question that remains unclear to me, that is how to define the full conversion, projection from entity to VM if needed to be fully custom - .Map just matches properties). If you need me to clarify let me know - but not that important, my main problem and more is solved now and I'm a happy man:)

Thanks a lot and sorry for bothering you - 

P.S. btw. if it's not an 'issue' but more a question where should I post things? here or Stackoverflow ? are you monitoring that?

**Comment by chaowlert** [comment]
You can suggest idea if things don't make sense. `Map` is to map a property. If you would like to control your own mapping you can use `MapWith`.

You can post issues here. I haven't monitor Stackoverflow.

**Comment by nsgaga** [comment]
all is fine, thanks!
when I learn Mapster code a bit more I may have some suggestions (if there is a need).
