### ISSUE TITLE
Mapping from a primitive to a class type doesn't work

### ISSUE THREAD

**Issue by bVanHertum** [eswann/Mapster#85]
I get an invalid cast exception, so Mapster seems to try to cast it straight up, ignoring the defined mapping:

```C#
public class ModelBase
{
	public string BaseString { get; set; }
	public List<MemberModel> Members { get; set; }
}

public void TestMapster2()
{
	TypeAdapterConfig<string, ModelBase>
		.ForType()
		.ConstructUsing(s => new ModelBase {BaseString = s});

	var result = "Bla".Adapt<string, ModelBase>();
}
```

Why I need this: My project uses a lot of small classes for which the string representation is used on the view model; each class has a Parse() method to reparse the string version, (so above, just do a SomeClass.Parse() instead of the new ModelBase), but I keep getting exceptions from Mapster.

**Comment by chaowlert** [comment]
PS. if your class have `Parse` method. Mapping could be success without config.

**Comment by bVanHertum** [comment]
Thanks, that worked.

As for the Parse method: it's contained in a base Identifier class, not the class itself, and Mapster doesn't seem to handle that. When I tested it on a class with a native Parse method, it worked just fine.
