### ISSUE TITLE
Mapping complex collection to flattened collection

### ISSUE THREAD

**Issue by centur** [eswann/Mapster#9]
It's be nice to have an example on how to map things like property of type Dictionary<string,Foo> into List<Bar> with  internal mapping like Foo->Bar with defaults but Bar.ParentKey receives value from Key in KeyValuePair<string,Foo>. 
I've tried few options but struggling to get it working. Although it looks like very simple scenario, default mappings from Foo to Bar are not being used or lost (or I'm doing something wrong).

**Comment by shoaibshakeel381** [comment]
+1

**Comment by chaowlert** [comment]
Hi, problem was Mapster 1.0 did not support Dictionary and struct like KeyValuePair. This should work in Mapster 2.0.
