### ISSUE TITLE
Nested complex type members are missed as flattened member sources

### ISSUE THREAD

**Issue by SteveWilkes** [eswann/Mapster#90]
Hi,

As per #89, mapping between the following members is having to be configured, instead of being found automatically by name matching:

Source:
 + Sub2
    +ProperName // <- doesn't match Sub2ProperName
 + SubWithExtraName
    +ProperName // <- doesn't match SubWithExtraNameProperName

Destination:
 + Sub2ProperName
 + SubWithExtraNameProperName

Cheers,

Steve

**Comment by chaowlert** [comment]
Mine is working fine, pls provide your test case.

```
    class Program
    {
        static void Main(string[] args)
        {
            var src = new Source
            {
                Sub2 = new SourceSub { ProperName = "A" },
                SubWithExtraName = new SourceSub { ProperName = "B" }
            };
            var dest = src.Adapt<Destination>();
            Console.WriteLine(dest.Sub2ProperName); //A
            Console.WriteLine(dest.SubWithExtraNameProperName); //B
        }
    }

    public class Source
    {
        public SourceSub Sub2 { get; set; }
        public SourceSub SubWithExtraName { get; set; }
    }

    public class SourceSub
    {
        public string ProperName { get; set; }
    }

    public class Destination
    {
        public string Sub2ProperName { get; set; }
        public string SubWithExtraNameProperName { get; set; }
    }
```

**Comment by SteveWilkes** [comment]
Here's a vs 2015 test project displaying the issue.

[MapsterNestedMapping.zip](https://github.com/eswann/Mapster/files/619722/MapsterNestedMapping.zip)

**Comment by chaowlert** [comment]
Ahh, thank you for test case. If there are a lot of properties with the same prefix. Mapster will work incorrectly.

**Comment by SteveWilkes** [comment]
No problem! It's easy to configure around, I just thought I'd flag it up :)
