### ISSUE TITLE
Option to prevent mapster from mapping Get... methods to properties.

### ISSUE THREAD

**Issue by alexeyosipov** [eswann/Mapster#91]
Hello, found now way to make mapster forget about GetType and other methods like this to do mapping on.

**Comment by chaowlert** [comment]
Yeah, sorry. GetType should be ignored from Get... methods. For now, you can remove Get... by

```
            TypeAdapterConfig.GlobalSettings.Default.Settings.ValueAccessingStrategies
                .Remove(ValueAccessingStrategy.GetMethod);
```
