### ISSUE TITLE
Can't map property of type Dictionary<int, Decimal> to the same prop.

### ISSUE THREAD

**Issue by alexeyosipov** [eswann/Mapster#92]
Imagine, I have class 

```
class A {
   public Dictionary<int, Decimal> Prop { get; set; }
}
```

Such code will rise an error:

`TypeAdapter.Adapt<A, A>(new A { Prop = new Dictionary<int, Decimal>{ { 1, 2m } }});`

Looks like [ConversionDictionary](https://github.com/eswann/Mapster#ConversionDictionary) rule applied here and rises exception.

**Comment by chaowlert** [comment]
Sorry for bug, I will fix this in this weekend. For now, could you please map manually?

```
            TypeAdapterConfig<Dictionary<int, decimal>, Dictionary<int, decimal>>.NewConfig()
                .MapWith(dict => dict.ToDictionary(kvp => kvp.Key, kvp => kvp.Value));

```
