### ISSUE TITLE
Generic types mapping

### ISSUE THREAD

**Issue by RaYell** [eswann/Mapster#98]
Is there any chance Mapster can map generic types? Something like.

```
config.ForType<SourceGeneric<T>, DestinationGeneric<T>>().Map(...)

MyGenericType<string> myType = new MyGenericType<string>();
myType.Adapt<MyOtherGenericType<string>>();
```

What I mean is I don't want to configure all potential types of `T` separately and would like to just define "generic mapping" between the types that will handle all types of `T`.

**Comment by chaowlert** [comment]
Mapster 3.0 now you can create config using generic definition (https://github.com/chaowlert/Mapster/wiki/Configuration#open-generics).
