### ISSUE TITLE
"Argument must be single dimensional array type" Exception when trying to map type with multi-dimensional array property

### ISSUE THREAD

**Issue by eborn** [eswann/Mapster#99]
Very simple example:
```C#
private static void Main()
{
    var a = new Foo { Ints = new int[2, 1] };
    var b = new Bar { Ints = new int[1, 2] };

    //throws exception
    TypeAdapter.Adapt(a, b);
}

internal class Foo
{
    public int[,] Ints { get; set; }
}

internal class Bar
{
    public int[,] Ints { get; set; }
}
```
I agree that multi-dimensional arrays are not the best thing, but still, even a reference copy would be a better behavior. The only workaround is to override the mapping with .MapWith but then again, see the other issue i'm reporting about MapToTargetWith.

**Comment by chaowlert** [comment]
Any contribution is welcome for this feature.
